-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO role (value, comment) VALUES
--   ('ADMIN', 'A role with every authorizations.'),
--   ('MANAGER', 'A role with some authorizations to manage service.'),
--   ('USER', 'A role of service user.'),
--   ('ANONYMOUS', 'A role of any unauthenticated access.');
