-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO idp (value) VALUES
--   ('GOOGLE'),
--   ('KAKAO'),
--   ('FACEBOOK'),
--   ('NAVER');
