version: 3
endpoint: http://localhost:8080 # This should be overrided
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000 # This should be overrided
